### ISSUE TITLE
Unable to control titan one with this plugin

### ISSUE THREAD

**Issue by pcmean** [bitfocus/companion-module-avolites-titan#1]
I am able to successfully connect this module to Titan one but from there I am unable to do anything.

**Comment by yyy898** [comment]
may i ask, what version of titan are you running ?

**Comment by yyy898** [comment]
This module uses the Webapi, the webapi is not available on a titan one, only titan mobile, T2 or physical avolights desks

**Comment by pcmean** [comment]
is there any way to have it work with titan one because titan one does have a remote app for your phone/tablet.

**Comment by yyy898** [comment]
at the moment there isnt, the app does use something very simular to the web api but its way more secured and i won't try to hack that security system.
I have spoken with the avolites people about this and they are not planning on implenting the webapi into titan one.

In my opinion the titan one is realy cheap and made to step into the software but if you want more features like midi control or webapi you have to switch to the T2

**Comment by pcmean** [comment]
I just want it so that when I put a slide up in pro presenter using companion to automatically change the color of the lights.

**Comment by pcmean** [comment]
thanks anyway.
