### ISSUE TITLE
no incoming level on (streaming ACN) trigger 

### ISSUE THREAD

**Issue by rawasyint** [bitfocus/companion-module-avolites-titan#10]
im using companion v2.3.0
and Avolites 15.1 (T1 dongle)
ip configuration 
pc and Avolites on deferent ip using Microsoft loop back adapter  and companion on local network 
i dont have incoming level streaming acn trigger  
here 
https://www.youtube.com/watch?v=wfzoi4ZX3Y0
its working .. but he did not show the steps 
starting by ip configuration to adding buttons 
and i cant  find the same buttons names in the new updates  (SACN: SET VALUE ) that he used 
i dont know if the naming changed 
thank u and i hope u can help me

**Comment by NijsJonas** [comment]
He used the sacn module, not the titan module.
This is not An issue for this moduel

**Comment by rawasyint** [comment]
ok sorry 
is sacn a module 
i cant find it in the Add connection  
I'm sorry  again

**Comment by NijsJonas** [comment]
> ok sorry is sacn a module i cant find it in the Add connection I'm sorry again

module is called "Generic Streaming ACN"
